version: "3.4"
services:
  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
      target: dev
      args:
        - SERVICE_NAME=client
    hostname: client
    container_name: client-bun
    command: sh -c "bun install && bun run dev"
    volumes:
      - ./client:/usr/src/client
    stdin_open: true
    tty: true
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}

  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile
      args:
        - SERVICE_NAME=server
    hostname: server
    container_name: server-bun
    command: sh -c "bun install && bun run dev"
    volumes:
      - ./server:/usr/src/server
    stdin_open: true
    tty: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}